### ISSUE TITLE
Handling named columns insertion

### ISSUE THREAD

**Issue by alex-dukhno** [alex-dukhno/database#103]
To align `insert_into` and `update_all` from `FrontendStorage` methods signature which could allow refactoring of the storage we need to implement named insert.

Query to reproduce:
```
create schema SMOKE_QUERIES;

create table SMOKE_QUERIES.VALIDATION_TABLE (column_1 smallint, column_2 smallint, column_3 smallint);

insert into SMOKE_QUERIES.VALIDATION_TABLE (column_1, column_2, column_3) values (1, 2, 3);
```

Expected result:
```
INSERT 0 <number of rows>
```

**Comment by silathdiir** [comment]
Hi @alex-dukhno , I'd like to work on this issue. Please assign it to me. Thanks.
