### ISSUE TITLE
Frontend Storage tests improvements

### ISSUE THREAD

**Issue by alex-dukhno** [alex-dukhno/database#141]
Currently, we have different helpers functions like `fn create_schema<P: backend::BackendStorage>(storage: &mut FrontendStorage<P>, schema_name: &str)` to setup fixture inside tests, but we can get advantages from using `rstest`.

Example function can be converted into:
```rust
#[rstest::fixture]
fn with_schema(mut storage: PersistentStorage) -> PersistentStorage {
  storage
        .create_schema("schema_name")
        .expect("no system errors")
        .expect("schema is created");
  storage
}
```
We need to check `rstest` docs if we could provide dynamic names for `schema_name` in case make tests more explicit

**Comment by Tolledo** [comment]
Hey @alex-dukhno, I'd like to work on this one. Can you please assign it to me
