### ISSUE TITLE
Add developer hint to type constraint violation error

### ISSUE THREAD

**Issue by alex-dukhno** [alex-dukhno/database#154]
Currently, constraints errors reports `<type> <constraint error message>`. It does not give much context for developers, we could either add value index or column name to `<constraint error message>`.

We can play around and add both or depending on how `insert` query is written. If it use column names like:
```sql
insert into table (col2, col1) values (32768, 0);
```
then error message could be like:
```
ERROR: smallint is out of range in col2 position
```
and if
```sql
insert into table values (32768, 0);
```
then error message could be like:
```
ERROR: smallint is out of range at 1 position
```

**Comment by Tolledo** [comment]
@alex-dukhno can you please assign to me?

**Comment by Tolledo** [comment]
@alex-dukhno, @AndrewBregger  I was looking around at examples of what error messages do other DBs have. MySQL gives the best hints for developers, by providing `column_name` and `row index`.

I guess explicit `column name` will be more useful for client then position index.

Error will look like:

```
ERROR: smallint is out of range for column 'col1' at row 1
```

What do you think?

**Comment by AndrewBregger** [comment]
I think using a column name and row number would be best. I am not sure if every situation those errors can be thrown a row number would make sense.
