### ISSUE TITLE
Implement Into<Vec<Message>> for QueryError and QueryEvent

### ISSUE THREAD

**Issue by alex-dukhno** [alex-dukhno/database#160]
Currently, `QueryError` has `into_message` function and `QueryEvent` is mapped to `Vec<Message>` in `QueryResultMapper`. The good way to unify is to implement `Into<Vec<Message>>` trait

**Comment by Tolledo** [comment]
@alex-dukhno can you please assign to me?

**Comment by alex-dukhno** [comment]
I believe that with these changes you should be able to remove `QueryResultMapper`. May I ask you to do that and update its tests to directly test `Into<Vec<Message>>` implementations of `QueryResult` and `QueryError`?

Thanks
