### ISSUE TITLE
Query Preprocessor

### ISSUE THREAD

**Issue by alex-dukhno** [alex-dukhno/database#166]
* [x] create schema
 * [x] drop schema
 * [x] create table
 * [x] drop table
 * [x] insert
 * [x] update
 * [x] select
 * [x] delete

We had a productive discussion with @AndrewB  about what we need to do with sql_engine that it can execute more sophisticated queries rather than `select * from <table_name>`. Here is a summary:
We agreed that we need a query preprocessor that has to read table definitions (list of column definitions) match names, types, and values, or return an error if something is going wrong. That means that if preprocessor finished its job we know that engine is going to run the query (assuming no runtime constraint errors).
All DML queries `select`s, `insert`s, `delete`s, and `update`s are going to be preprocessed because basic operations like #127 also require preprocessing.
Another immediate question is that database stores data in binary (basically `Vec<u8>`) and data from queries are coming as `String`s (at least right now) which then parsed, validated (with type constraints) and converted into `Vec<u8>`. Binary is efficient and good for `char`s, `var char`s, `blob`s type, but not convenient for `numeric` types, all operations like `+`, `-` and so on should be reimplemented. We somehow have to join these two worlds

**Comment by AndrewBregger** [comment]
@alex-dukhno Could you add me to this issue?

**Comment by alex-dukhno** [comment]
closing as all type of queries uses `Binary` and `Datum`. Improvements to how to represent internals of `Binary` should be tracked in another tickets
