### ISSUE TITLE
Abstract Secured Connection/Channel

### ISSUE THREAD

**Issue by alex-dukhno** [alex-dukhno/database#172]
Currently, protocol `QueryListener` and `ServerListener` uses two associated types `TcpChannel` and `TlsChannel`. This design doesn't allow to reuse protocol startup-flow logic.
We somehow need to abstract away `Channel` so that `protocol::Connection` could with it as simple pipe and `*Listener`s could reuse handshake logic

**Comment by silathdiir** [comment]
Hi @alex-dukhno , please assign this issue to me. I will try to fix it based on your draft PR https://github.com/alex-dukhno/database/pull/171. Thanks.
