### ISSUE TITLE
Use c-like enum variant in QueryErrorKind enum

### ISSUE THREAD

**Issue by alex-dukhno** [alex-dukhno/database#176]
`QueryErrorKind` is growing and its variants start containing long list of arguments. We can make it clearer using c-like enums like
```rust
enum QueryErrorKind {
    // ...
    NumericTypeOutOfRange{ pg_type: PostgreSqlType, col_name: String, row_index: usize }
}
```

**Comment by jayphbee** [comment]
HI @alex-dukhno  i'd like to take this issue
