### ISSUE TITLE
Implement Extended Query PostgreSQL Protocol

### ISSUE THREAD

**Issue by alex-dukhno** [alex-dukhno/database#177]
If I were asked to describe what is `"Extended Query PostgreSQL Protocol"`, I'd say it is `Prepared Statement` over wire.
As far as I understand (right now) query is sent in form of the string like `select * from table where col1 = $1;` or `insert into table values ($1, $2, $3);` and then data bindings negotiated between client and server.

Doc https://www.postgresql.org/docs/12/protocol-flow.html#PROTOCOL-FLOW-EXT-QUERY

Quick search over Materialize source code gave me https://github.com/MaterializeInc/materialize/blob/main/src/pgwire/src/protocol.rs#L114 as possible entry point to start getting info of how "prepared statement" state could be managed

**Comment by silathdiir** [comment]
Hi @alex-dukhno , I'd like to work on this issue after PR #184 is reviewed and merged.
