### ISSUE TITLE
Move type constraint checks from Storage to Sql Engine

### ISSUE THREAD

**Issue by alex-dukhno** [alex-dukhno/database#202]
As a result of #197, multiple errors could be sent one by one instead of `Vec<QueryErrorInner>`.
As I don't see value of introducing dependency between `protocol` and `storage` type constraint checks should be moved to SQL engine module

**Comment by AndrewBregger** [comment]
@alex-dukhno In PR #199  type checking has been removed from the insert and some of the type checkings has been moved to sql_engine.
