### ISSUE TITLE
Datum construction from incoming data from client

### ISSUE THREAD

**Issue by alex-dukhno** [alex-dukhno/database#218]
> `Datum::try_from` should accept also `SqlType` or `Constraint` to validate and then convert to appropriate `Datum` variant.
>
> That should fix the regression with booleans https://github.com/alex-dukhno/database/blob/master/tests/functional/test_queries_with_sql_types.py#L70
>
> and strings https://github.com/alex-dukhno/database/blob/master/src/sql_engine/src/tests/select.rs#L338

Currently, one of the idea is to create `Datum` after constraint validation after API changes to `Constraint` #310 if they are possible

**Comment by vkulichenko** [comment]
@alex-dukhno I can work on this. Can you please assign?

**Comment by alex-dukhno** [comment]
Hi @vkulichenko, I hope you have done much work on this issue. After resent improvements and discussion on discord channel I think we'll have different direction with constraint validation. I put `Triage` label to have a look on issue description later.
