### ISSUE TITLE
On Disk representation research

### ISSUE THREAD

**Issue by alex-dukhno** [alex-dukhno/database#221]
Currently, on disk representation (in module `representation`) is heavily influenced by Materialize.

As no other option weren't discussed or investigated I'd like to make some research on this topic.
Obvious candidate to have look at:
* PostgreSQL
* CockroachDB
* MySQL
* SQLite
* MariaDB

**Comment by AndrewBregger** [comment]
@alex-dukhno I have started to do some research into On-Disk Representation. I am wondering what you have discovered and how do you think would be the best method for discussion on this topic.

**Comment by alex-dukhno** [comment]
Hi @AndrewBregger thanks for being initiative.
This week was busy for me. We are going to have release next week and I've moved to new apartment so not all things are settled down.
I was starting to watch [08 - Database Storage Models & Layout (CMU Databases / Spring 2020)](https://www.youtube.com/watch?v=y6qFHu0YKMM&list=PLSE8ODhjZXjasmrEd2_Yi1deeE360zv5O&index=8) from Andy Pavlo where he said that he gave previous 4 lectures on Indexes and MVCC because it influence storage models & layout - I did think of that before. So I decided to go through both his courses [Advanced Database Systems](https://15721.courses.cs.cmu.edu/spring2020/) and [Database Systems](https://15445.courses.cs.cmu.edu/fall2019/) with readings linked to lectures.

For now I don't have much info or ideas. But this is insights I had:
 1. NewSQL (e.g. CockraochDB) 
    * aiming to not to stall transaction with disk IO and use it to backed what is in RAM (so called main memory databases). This leads me to think to rewrite `FrontendStorage` as a write through cache in front of `BackendStorage`.
    * partitioning data to speedup operation (less network traffic and other perf optimisation is possible for query execution)
 2. Relational DB from previous century (e.g. MySQL, PostrgreSQL) had different problems. One is that the RAM wasn't cheap as today, so they should store and manage data on disk.

Right now what I'd like to have is a list of databases, what on disk representation they have and what use cases they are/were targeting.

I understand that it is a very vague description but I don't have full picture/list of what use cases I'd like to target for the database that we are building. I hope to find them in flow of the information.

**Comment by alex-dukhno** [comment]
> The representation of a record with variable-length attributes typically has two  parts: an initial part with fixed-length information, whose structure is the same for  all records of the same relation, followed by the contents of variable-length attributes.  Fixed-length attributes, such as numeric values, dates, or fixed-length character strings  are allocated as many bytes as required to store their value. Variable-length attributes,  such as varchar types, are represented in the initial part of the record by a pair (off-  set, length), where offset denotes where the data for that attribute begins within the  record, and length is the length in bytes of the variable-sized attribute. The values for  the variable-length attributes are stored consecutively, after the initial fixed-length part  of the record. Thus, the initial part of the record stores a fixed size of information about  each attribute, whether it is fixed-length or variable-length. 
> Silberschatz, Abraham. Database System Concepts (p. 592). McGraw-Hill Higher Education. Kindle Edition. 

>The figure also illustrates the use of a null bitmap, which indicates which attributes  of the record have a null value.
>Silberschatz, Abraham. Database System Concepts (p. 593). McGraw-Hill Higher Education. Kindle Edition. 

I liked this two ideas how to store variable length types
They are from `File Organisation` chapter

**Comment by AndrewBregger** [comment]
New releases and moving are always stressful.

I need to do more academic research into how these systems should work. The classes you mentioned previously and actual research papers about these topics are a good place to start for this. The Advanced Database Systems class has some current research papers for each topic discussed.

I think `FrontendStorage` should be an abstraction for interacting with in-memory objects and on-disk objects. As well as managing the interaction between the two. It seems that was the original purpose. To me `FrontendStorage` should look something like:

```rust
struct FrontendStorage {
    disk_storage: BackendStorage,
    in_memory: MemoryStorage,
    <whatever else is needed>
}
```

**Comment by AndrewBregger** [comment]
> partitioning data to speedup operation

I think this is very important. `Sled` should be storing these partitions or a collection of partitions (this really depends on the size of the partitions).

**Comment by alex-dukhno** [comment]
> Sled should be storing these partitions or a collection of partitions (this really depends on the size of the partitions).

The more I research on this topic the more I want to dig through `sled` codebase. And probably I have to get aquatinted with [The Bw-Tree: A B-tree for New Hardware Platforms](https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/bw-tree-icde2013-final.pdf) as `sled` us BwTree

**Comment by alex-dukhno** [comment]
I think we should go with ideas for the book quoted in https://github.com/alex-dukhno/database/issues/221#issuecomment-667706928 that allow us to do `Binary::get(index) -> value` and `Binary::put(index, value)`
