### ISSUE TITLE
If PGJDBC does not close connection it crashes database on next connection

### ISSUE THREAD

**Issue by alex-dukhno** [alex-dukhno/database#354]
Reproducer
```groovy
db = Sql.newInstance(dbConf())
db.execute 'create schema SCHEMA_NAME'
db.execute 'insert into SCHEMA_NAME.TABLE_NAME values (1, 2, 3), (4, 5, 6), (7, 8, 9)'

db = Sql.newInstance(dbConf())
db.execute 'select * from SCHEMA_NAME.TABLE_NAME'
```

Database logs:
```
DEBUG [protocol] client request message tag 88
DEBUG [protocol::messages] Receives frontend tag = 'X', buffer = []
DEBUG [protocol] client request message Terminate
DEBUG [node::query_engine] closing connection with client
DEBUG [protocol] stop service of connection-5
ERROR [node::node] UNEXPECTED ERROR: Kind(UnexpectedEof)
DEBUG [protocol] stop service of connection-2
ERROR [node::node] UNEXPECTED ERROR: Kind(UnexpectedEof)
DEBUG [protocol] stop service of connection-3
ERROR [node::node] UNEXPECTED ERROR: Kind(UnexpectedEof)
DEBUG [protocol] stop service of connection-1
ERROR [node::node] UNEXPECTED ERROR: Kind(UnexpectedEof)
DEBUG [protocol] stop service of connection-4
DEBUG [protocol] address V4(127.0.0.1:60030)
DEBUG [protocol] client is trying to connect with version 3
DEBUG [protocol] client message response tag Ok(112)
DEBUG [protocol] waiting for authentication response
DEBUG [protocol] start service on connection-5
DEBUG [protocol] send ready_for_query message
DEBUG [protocol] stop service of connection-5
```

**Comment by silathdiir** [comment]
Hi @alex-dukhno , I tried to reproduce the above issue in `groovysh` (as below). I could not find the error log `UNEXPECTED ERROR: Kind(UnexpectedEof)`.

```
groovysh
groovy:000>

:grab org.postgresql:postgresql:9.4-1205-jdbc42
import groovy.sql.Sql

dbConf = [
  url: "jdbc:postgresql://localhost:5432/test?gssEncMode=disable&sslmode=disable&preferQueryMode=extendedForPrepared",
  user: "postgres",
  password: "postgres",
  driver: "org.postgresql.Driver",
]

db = Sql.newInstance(dbConf)
db.execute 'create schema SCHEMA_NAME'
db.execute 'insert into SCHEMA_NAME.TABLE_NAME values (1, 2, 3), (4, 5, 6), (7, 8, 9)'

db = Sql.newInstance(dbConf())
db.execute 'select * from SCHEMA_NAME.TABLE_NAME'
```

But it seems that Schema cannot been created via Extended Query.

```
DEBUG [sqlparser::parser] Parsing sql 'create schema SCHEMA_NAME'...
DEBUG [data_manager::data_definition] checking schema existence "public"."schema_name"
ERROR [node::query_engine] Error while planning not supported extended query for CreateSchema(SchemaCreationInfo { schema_name: "schema_name" })
```

I tried with `psql`. It seems that `UnexpectedEof` occurred when starting with command `psql -h localhost` (without `-W`).

```
psql -h localhost

DEBUG [protocol] address V4(127.0.0.1:52256)
DEBUG [protocol] client is trying to connect with SSL
DEBUG [protocol] client is trying to connect with version 3
DEBUG [protocol] client message response tag Err(Kind(UnexpectedEof))
DEBUG [protocol] waiting for authentication response
ERROR [node::node] IO error Kind(UnexpectedEof)
DEBUG [protocol] address V4(127.0.0.1:52258)
```

I think it should not be the same issue. Could you help describe the detail reproduced steps? I could try to fix it. Thanks.

**Comment by alex-dukhno** [comment]
Hi, thanks for looking into this one.

First, it is not related to the issue but it is strange that you can't create schema. Yes `CREATE SCHEMA` query does not work with extended query protocol right now (I am working on infrastructure code to fix this), but you have `preferQueryMode=extendedForPrepared` connection params, and AFAIK `Sql.execute(String)` doesn't use `PreparedStatement`. Can you try it with `preferQueryMode=simple`?

I actually noticed the issue while running compatibility tests.
If you start database and comment out the line https://github.com/alex-dukhno/database/blob/master/tests/compatibility/src/test/groovy/io/database/ThreeSmallIntColumnTable.groovy#L28
and run `./local/compatibility.sh` for several times database should crash.

P.S.: I was starting to suspect that not closing connections we exhausting `smol` thread pool https://github.com/alex-dukhno/database/blob/master/src/node/src/node.rs#L68-L89 but we do return from future when we encounter error
https://github.com/alex-dukhno/database/blob/master/src/node/src/node.rs#L74
https://github.com/alex-dukhno/database/blob/master/src/node/src/node.rs#L79

😄 I probably know what the issue is ... `state` is changed to `STOPPED` when we get an error and then we return from future that we submit to ` smol::block_on`
https://github.com/alex-dukhno/database/blob/master/src/node/src/node.rs#L62
https://github.com/alex-dukhno/database/blob/master/src/node/src/node.rs#L44
