### ISSUE TITLE
Cover the case of creating table without columns

### ISSUE THREAD

**Issue by alex-dukhno** [alex-dukhno/database#68]
It is actually possible, reproducer:
```
[alex-dukhno@Alexs-MacBook-Pro ~]$ docker exec -it some-postgres /bin/bash
root@bc37e2936baa:/# psql -U postgres
psql (12.2 (Debian 12.2-2.pgdg100+1))
Type "help" for help.

postgres=# create table empty ();
CREATE TABLE
postgres=# select * from empty;
--
(0 rows)

postgres=# insert into empty values();
ERROR:  syntax error at or near ")"
LINE 1: insert into empty values();
                                 ^
postgres=# insert into empty values(1);
ERROR:  INSERT has more expressions than target columns
LINE 1: insert into empty values(1);
                                 ^
postgres=# insert into empty values(null);
ERROR:  INSERT has more expressions than target columns
LINE 1: insert into empty values(null);
                                 ^
```

**Comment by silathdiir** [comment]
Hi @alex-dukhno , I am starting to look into the code. May I work on this issue?

**Comment by alex-dukhno** [comment]
Hi, @silathdiir sure. Thanks for picking it up

**Comment by alex-dukhno** [comment]
BTW, if you have any questions don't hesitate to reach me out. I am glad to help :)

**Comment by silathdiir** [comment]
Hi @alex-dukhno , Thank you. I started to build and run the project with `cargo run`.
And I tested on `psql` with the below SQLs (according to folder `compatibility`).

```
create schema SMOKE_QUERIES;

create table SMOKE_QUERIES.EMPTY_TABLE ();

select * from SMOKE_QUERIES.EMPTY_TABLE;

drop table SMOKE_QUERIES.EMPTY_TABLE;

drop schema SMOKE_QUERIES;
```

It seems that EMPTY table has already been supported (on protocol part?). I tries to start reviewing the `src/storage` code.

***Could you help give some general instructions about which part should I step into first? Thanks a lot.***

**Comment by alex-dukhno** [comment]
Hi, honestly, I forgot what triggers me to create this issue - 😂 
However, communication protocol hasn't to be a problem, but I see three cases of the problem, `insert`, `update` and `delete` - and now I am thinking that all of them are edge cases.

For instance: 
* `insert` into empty table is more like inserting "more" values than rows in a table.
* `delete` and `update` when user incorrectly specified column(s) names

**Comment by alex-dukhno** [comment]
I think I have to create at least four issue, and all of them `good first issues`. I will ping you here and let you to choose any of them 😄

**Comment by alex-dukhno** [comment]
@silathdiir here are they #70, #71 and #72 pick any of them. I tried to describe as much as possible with places and methods to look at. I think #70 should be much easier than other two, because it already use code that should be re-used in #71 and #72.

And thank you for contribution! Now I know how I should describe `good first issue`(s) 😄
