### ISSUE TITLE
handle error when user selects column that is not in the table

### ISSUE THREAD

**Issue by alex-dukhno** [alex-dukhno/database#70]
Query to reproduce:
```sql
create schema schema_name;
create table schema_name.table_name (column_in_table smallint);
select column_not_in_table from schema_name.table_name;
```

Expected result in `psql`:
```
ERROR: column "column_not_in_table" does not exist
```
additionally it could say the error line in query after the error message, like:
```
LINE 1: select col1 from empty;
```

Actual result:
```
select column_not_in_table from schema_name.table_name;
 column_not_in_table
---------------------
(0 rows)
```

The module to have a look is `storage/src/frontend/mod.rs`.
There is a method:
```
pub fn select_all_from(
        &mut self,
        schema_name: &str,
        table_name: &str,
        columns: Vec<String>,
    ) -> SystemResult<Result<Projection, OperationOnTableError>>
```
Before performing a query it reads table columns with `self.table_columns(schema_name, table_name)?`
so we have to add the check if column(s) in the table
also `sql_engine` module and `QueryResultMapper` in `node` module have to be updated respectively

**Comment by silathdiir** [comment]
Hi @alex-dukhno , Thanks for the clear description!
I will start to work on this issue. Thank you.
