### ISSUE TITLE
handle error when user is trying to insert into a table more values than it has columns

### ISSUE THREAD

**Issue by alex-dukhno** [alex-dukhno/database#71]
SQL to reproduce:
```sql
create schema schema_name;
create table schema_name.table_name (column_in_table smallint);
insert into schema_name.table_name values (1, 2);
```

Expected result in `psql`:
```
ERROR:  INSERT has more expressions than target columns
```
additionally print line with the error like:
```
LINE 1: insert into empty values(1);
```

Actual result:
```
insert into schema_name.table_name values (1, 2);
INSERT 0 1
```

`storage/src/frontend/mod.rs` method
```rust
    pub fn insert_into(
        &mut self,
        schema_name: &str,
        table_name: &str,
        values: Vec<Vec<String>>,
    ) -> SystemResult<Result<(), OperationOnTableError>> {
```
does not check the number of columns in a table

**Comment by AndrewBregger** [comment]
Hello @alex-dukhno, I would like to contribute to this project. Do you know if anyone is working on this issue? If not, I would like to.

**Comment by alex-dukhno** [comment]
Hi @AndrewBregger, generally speaking, if no one is assigned then no one is working on it 😄
So yeah, you can start working on it.
The only thing is that I hope @silathdiir is not going to implement it in #124.
If it is bothering you, the other variant is #76

**Comment by AndrewBregger** [comment]
Alright, good to know., Since @silathdiir work on #124 could also resolve this issue, I will work on #76.

**Comment by silathdiir** [comment]
The PR #124 has already been merged. But this issue has not been fixed yet. Please feel free to take it.
