### ISSUE TITLE
handle error when user is trying to update column that is not in a table

### ISSUE THREAD

**Issue by alex-dukhno** [alex-dukhno/database#72]
SQL to reproduce:
```sql
create schema schema_name;
create table schema_name.table_name (column_in_table smallint);
insert into schema_name.table_name values (1);
update schema_name.table_name set column_not_in_table = 2;
```

Expected result in `psql`:
```
ERROR:  column "column_not_in_table" of relation "schema_name.table_name" does not exist
```
additionally we can print line with an error like
```
update schema_name.table_name set column_not_in_table = 2;
```

Actual result:
```
UPDATE 1;
```

`storage/src/frontend/mod.rs` method
```
pub fn update_all(
        &mut self,
        schema_name: &str,
        table_name: &str,
        value: String,
    ) -> SystemResult<Result<usize, OperationOnTableError>> {
```
is not checking what column names is in a table before performing update

**Comment by silathdiir** [comment]
Hi @alex-dukhno , I'd like to work on this issue if appropriate.

**Comment by alex-dukhno** [comment]
All `good first issue` and `help wanted` are appropriate 😄 
Don't hesitate to pick any of them, just notify me so I could assign you - just so others know that someone is looking into the issue
