### ISSUE TITLE
Improvements to QueryError

### ISSUE THREAD

**Issue by alex-dukhno** [alex-dukhno/database#76]
Currently, `QueryError` is an enum and uses `thiserror` to generate `Display` trait but it is not allow conditional message generation.
This ticket imply the following tasks:
* convert `QueryError` into `struct` with fields `severity`, `code` and `kind`
* create enum `Severity` with variants specified for `S` field in PostrgreSQL protocol
* create enum `kind` which has current `QueryError` variants `SchemaDoesNotExist` and others
* field code `String` type

Also implement convenient constructors for different error `kind`s

e.g.:
```rust
impl QueryError {
    pub fn schema_does_not_exists(schema_name: String) -> Self {
        Self {
            kind: ErrorKind::SchemaDoesNotExist(schema_name),
            code: "3F000".to_owned(),
            severity: Severity::Error
        }
    }
}
```

**Comment by alex-dukhno** [comment]
@AndrewBregger as GH is not allowing me to assign you to the issue, I'll assign myself.

**Comment by AndrewBregger** [comment]
@alex-dukhno I have finished this issue. I didn't realize you were trying to move away from thiserror. I need to fix this.

**Comment by alex-dukhno** [comment]
@AndrewBregger sorry I didn't mention it explicitly in the issue description. Something that I have to work on "describe ideas more clearly and fully" 😄
