### ISSUE TITLE
Support approximate types constraints

### ISSUE THREAD

**Issue by alex-dukhno** [alex-dukhno/database#91]
part of #17

see `real` and `double precision` at https://www.postgresql.org/docs/12/datatype-numeric.html

`f32` and `f64` can be used to store data for `real` and `double precision` respectively

`SqlType::SmallInt`, `SqlType::Integer` and `SqlType::BigInt` can be used as a reference implémentation

**Comment by Tolledo** [comment]
@alex-dukhno please assign to me.
