### ISSUE TITLE
Support serial data types

### ISSUE THREAD

**Issue by alex-dukhno** [alex-dukhno/database#96]
Support `smallserial` `serial` and `bigserial` sql types see https://www.postgresql.org/docs/12/datatype-numeric.html

It is possible to do by updating `SqlType::SmallInt`, `SqlType::Integer` and `SqlType::BigInt` respectively by extending enum variants with `min` possible value field

**Comment by suhaibaffan** [comment]
Hello @alex-dukhno want to work on this issue, please assign it to me.

**Comment by alex-dukhno** [comment]
Hi sure 😄
